sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.5
    - 5.6
    - 7.0
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

before_install:
    - if ([ "hhvm" != "$TRAVIS_PHP_VERSION" ] && [ "nightly" != "$TRAVIS_PHP_VERSION" ]); then wget https://scrutinizer-ci.com/ocular.phar; fi
    - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
    - rm -rf tests/Functional/cache/*

install:
    - composer update --prefer-dist

script:
    - php console -V
    - phpunit --coverage-text
    - vendor/bin/behat

after_script:
    - if ([ "hhvm" != "$TRAVIS_PHP_VERSION" ] && [ "nightly" != "$TRAVIS_PHP_VERSION" ]); then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi

notifications:
    email: false
